# Generated by Django 5.2.6 on 2025-09-16 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('nib_size', models.CharField(choices=[('EF', 'Extra Fine'), ('F', 'Fine'), ('M', 'Medium'), ('B', 'Bold')], default='EF', max_length=2)),
                ('nib_material', models.CharField(choices=[('S', 'Steel'), ('G14', 'Gold 14k'), ('G18', 'Gold 18k'), ('G21', 'Gold 21k'), ('T', 'Titanium'), ('P', 'Platinum'), ('B', 'Bronze'), ('G', 'Glass')], default='S', max_length=3)),
                ('ink_fill', models.CharField(choices=[('CA', 'Cartridge'), ('CO', 'Cartridge-Converter'), ('P', 'Piston-Fill'), ('V', 'Vacuum-Fill')], default='CA', max_length=2)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
