# Generated by Django 5.2.6 on 2025-09-16 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='acquired_date',
            field=models.DateField(blank=True, null=True, verbose_name='Acquired Date'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_material',
            field=models.CharField(choices=[('SS', 'Stainless Steel'), ('G14', 'Gold 14k'), ('G18', 'Gold 18k'), ('G21', 'Gold 21k'), ('T', 'Titanium'), ('P', 'Platinum'), ('B', 'Bronze'), ('G', 'Glass')], default='SS', max_length=3),
        ),
        migrations.AlterField(
            model_name='pen',
            name='nib_size',
            field=models.CharField(choices=[('EF', 'Extra Fine'), ('F', 'Fine'), ('M', 'Medium'), ('B', 'Bold'), ('S', 'Stub')], default='EF', max_length=2),
        ),
    ]
