# Generated by Django 5.2.6 on 2025-09-16 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_pen_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('color_family', models.CharField(choices=[('BL', 'Blue'), ('B', 'Black'), ('BR', 'Brown'), ('G', 'Green'), ('R', 'Red'), ('PU', 'Purple'), ('O', 'Orange'), ('PI', 'Pink'), ('Y', 'Yellow')], default='BL', max_length=2)),
                ('shimmer', models.BooleanField(default=False)),
                ('sheen', models.BooleanField(default=False)),
                ('acquired_date', models.DateField(verbose_name='Acquired Date')),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='pen',
            name='inks',
            field=models.ManyToManyField(to='main_app.ink'),
        ),
    ]
