# Generated by Django 5.2.6 on 2025-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_ink_pen_inks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ink',
            name='color_family',
        ),
        migrations.AddField(
            model_name='ink',
            name='color',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
