# Generated by Django 5.2.6 on 2025-09-17 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_ink_color_family_ink_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pen',
            name='inks',
            field=models.ManyToManyField(blank=True, to='main_app.ink'),
        ),
        migrations.AlterField(
            model_name='pen',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
