# Generated by Django 5.2.6 on 2025-09-18 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_pen_inks_alter_pen_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='size',
            field=models.CharField(choices=[('B', 'Bottle'), ('S', 'Sample')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='pen',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
