# Generated by Django 5.2.6 on 2025-09-19 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_ink_size_alter_pen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ink',
            name='hex_code',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AddField(
            model_name='ink',
            name='swatch_img',
            field=models.ImageField(blank=True, null=True, upload_to='swatches/'),
        ),
    ]
