# Generated by Django 5.2.6 on 2025-09-23 14:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ink_hex_code_ink_swatch_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ink',
            name='acquired_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Acquired Date'),
        ),
        migrations.CreateModel(
            name='PenInkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inked', models.DateField(default=django.utils.timezone.now, verbose_name='Date Inkted')),
                ('date_cleaned', models.DateField(blank=True, null=True, verbose_name='Date Cleaned')),
                ('ink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pen_logs', to='main_app.ink')),
                ('pen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ink_logs', to='main_app.pen')),
            ],
        ),
    ]
